# Generated by Django 3.1.7 on 2021-04-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0002_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=0, upload_to='images'),
        ),
    ]
